<?php

namespace Database\Seeders;

use App\Models\Municipio;
use App\Models\Departamento;
use Illuminate\Database\Seeder;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        deshabilitaLlavesForaneas();
        Municipio::truncate();

        $municipios = [
            // 01 - Guatemala
            ['codigo' => '0101', 'nombre' => 'GUATEMALA', 'departamento_codigo' => '01'],
            ['codigo' => '0102', 'nombre' => 'SANTA CATARINA PINULA', 'departamento_codigo' => '01'],
            ['codigo' => '0103', 'nombre' => 'SAN JOSÉ PINULA', 'departamento_codigo' => '01'],
            ['codigo' => '0104', 'nombre' => 'SAN JOSÉ DEL GOLFO', 'departamento_codigo' => '01'],
            ['codigo' => '0105', 'nombre' => 'PALENCIA', 'departamento_codigo' => '01'],
            ['codigo' => '0106', 'nombre' => 'CHINAUTLA', 'departamento_codigo' => '01'],
            ['codigo' => '0107', 'nombre' => 'SAN PEDRO AYAMPUC', 'departamento_codigo' => '01'],
            ['codigo' => '0108', 'nombre' => 'MIXCO', 'departamento_codigo' => '01'],
            ['codigo' => '0109', 'nombre' => 'SAN PEDRO SACATEPÉQUEZ', 'departamento_codigo' => '01'],
            ['codigo' => '0110', 'nombre' => 'SAN JUAN SACATEPÉQUEZ', 'departamento_codigo' => '01'],
            ['codigo' => '0111', 'nombre' => 'SAN RAYMUNDO', 'departamento_codigo' => '01'],
            ['codigo' => '0112', 'nombre' => 'CHUARRANCHO', 'departamento_codigo' => '01'],
            ['codigo' => '0113', 'nombre' => 'FRAIJANES', 'departamento_codigo' => '01'],
            ['codigo' => '0114', 'nombre' => 'AMATITLÁN', 'departamento_codigo' => '01'],
            ['codigo' => '0115', 'nombre' => 'VILLA NUEVA', 'departamento_codigo' => '01'],
            ['codigo' => '0116', 'nombre' => 'VILLA CANALES', 'departamento_codigo' => '01'],
            ['codigo' => '0117', 'nombre' => 'PETAPA', 'departamento_codigo' => '01'],
            ['codigo' => '0199', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '01'],

            // 02 - El Progreso
            ['codigo' => '0201', 'nombre' => 'GUASTATOYA', 'departamento_codigo' => '02'],
            ['codigo' => '0202', 'nombre' => 'MORAZÁN', 'departamento_codigo' => '02'],
            ['codigo' => '0203', 'nombre' => 'SAN AGUSTÍN ACASAGUASTLÁN', 'departamento_codigo' => '02'],
            ['codigo' => '0204', 'nombre' => 'SAN CRISTÓBAL ACASAGUASTLÁN', 'departamento_codigo' => '02'],
            ['codigo' => '0205', 'nombre' => 'EL JÍCARO', 'departamento_codigo' => '02'],
            ['codigo' => '0206', 'nombre' => 'SANSARE', 'departamento_codigo' => '02'],
            ['codigo' => '0207', 'nombre' => 'SANARATE', 'departamento_codigo' => '02'],
            ['codigo' => '0208', 'nombre' => 'SAN ANTONIO LA PAZ', 'departamento_codigo' => '02'],
            ['codigo' => '0299', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '02'],

            // 03 - Sacatepéquez
            ['codigo' => '0301', 'nombre' => 'ANTIGUA GUATEMALA', 'departamento_codigo' => '03'],
            ['codigo' => '0302', 'nombre' => 'JOCOTENANGO', 'departamento_codigo' => '03'],
            ['codigo' => '0303', 'nombre' => 'PASTORES', 'departamento_codigo' => '03'],
            ['codigo' => '0304', 'nombre' => 'SUMPANGO', 'departamento_codigo' => '03'],
            ['codigo' => '0305', 'nombre' => 'SANTO DOMINGO XENACOJ', 'departamento_codigo' => '03'],
            ['codigo' => '0306', 'nombre' => 'SANTIAGO SACATEPÉQUEZ', 'departamento_codigo' => '03'],
            ['codigo' => '0307', 'nombre' => 'SAN BARTOLOMÉ MILPAS ALTAS', 'departamento_codigo' => '03'],
            ['codigo' => '0308', 'nombre' => 'SAN LUCAS SACATEPÉQUEZ', 'departamento_codigo' => '03'],
            ['codigo' => '0309', 'nombre' => 'SANTA LUCÍA MILPAS ALTAS', 'departamento_codigo' => '03'],
            ['codigo' => '0310', 'nombre' => 'MAGDALENA MILPAS ALTAS', 'departamento_codigo' => '03'],
            ['codigo' => '0311', 'nombre' => 'SANTA MARÍA DE JESÚS', 'departamento_codigo' => '03'],
            ['codigo' => '0312', 'nombre' => 'CIUDAD VIEJA', 'departamento_codigo' => '03'],
            ['codigo' => '0313', 'nombre' => 'SAN MIGUEL DUEÑAS', 'departamento_codigo' => '03'],
            ['codigo' => '0314', 'nombre' => 'ALOTENANGO', 'departamento_codigo' => '03'],
            ['codigo' => '0315', 'nombre' => 'SAN ANTONIO AGUAS CALIENTES', 'departamento_codigo' => '03'],
            ['codigo' => '0316', 'nombre' => 'SANTA CATARINA BARAHONA', 'departamento_codigo' => '03'],
            ['codigo' => '0399', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '03'],

            // 04 - Chimaltenango
            ['codigo' => '0401', 'nombre' => 'CHIMALTENANGO', 'departamento_codigo' => '04'],
            ['codigo' => '0402', 'nombre' => 'SAN JOSÉ POAQUIL', 'departamento_codigo' => '04'],
            ['codigo' => '0403', 'nombre' => 'SAN MARTÍN JILOTEPEQUE', 'departamento_codigo' => '04'],
            ['codigo' => '0404', 'nombre' => 'COMALAPA', 'departamento_codigo' => '04'],
            ['codigo' => '0405', 'nombre' => 'SANTA APOLONIA', 'departamento_codigo' => '04'],
            ['codigo' => '0406', 'nombre' => 'TECPÁN GUATEMALA', 'departamento_codigo' => '04'],
            ['codigo' => '0407', 'nombre' => 'PATZÚN', 'departamento_codigo' => '04'],
            ['codigo' => '0408', 'nombre' => 'POCHUTA', 'departamento_codigo' => '04'],
            ['codigo' => '0409', 'nombre' => 'PATZICÍA', 'departamento_codigo' => '04'],
            ['codigo' => '0410', 'nombre' => 'SANTA CRUZ BALANYÁ', 'departamento_codigo' => '04'],
            ['codigo' => '0411', 'nombre' => 'ACATENANGO', 'departamento_codigo' => '04'],
            ['codigo' => '0412', 'nombre' => 'YEPOCAPA', 'departamento_codigo' => '04'],
            ['codigo' => '0413', 'nombre' => 'SAN ANDRÉS ITZAPA', 'departamento_codigo' => '04'],
            ['codigo' => '0414', 'nombre' => 'PARRAMOS', 'departamento_codigo' => '04'],
            ['codigo' => '0415', 'nombre' => 'ZARAGOZA', 'departamento_codigo' => '04'],
            ['codigo' => '0416', 'nombre' => 'EL TEJAR', 'departamento_codigo' => '04'],
            ['codigo' => '0499', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '04'],

            // 05 - Escuintla
            ['codigo' => '0501', 'nombre' => 'ESCUINTLA', 'departamento_codigo' => '05'],
            ['codigo' => '0502', 'nombre' => 'SANTA LUCÍA COTZUMALGUAPA', 'departamento_codigo' => '05'],
            ['codigo' => '0503', 'nombre' => 'LA DEMOCRACIA', 'departamento_codigo' => '05'],
            ['codigo' => '0504', 'nombre' => 'SIQUINALÁ', 'departamento_codigo' => '05'],
            ['codigo' => '0505', 'nombre' => 'MASAGUA', 'departamento_codigo' => '05'],
            ['codigo' => '0506', 'nombre' => 'TIQUISATE', 'departamento_codigo' => '05'],
            ['codigo' => '0507', 'nombre' => 'LA GOMERA', 'departamento_codigo' => '05'],
            ['codigo' => '0508', 'nombre' => 'GUANAGAZAPA', 'departamento_codigo' => '05'],
            ['codigo' => '0509', 'nombre' => 'SAN JOSÉ', 'departamento_codigo' => '05'],
            ['codigo' => '0510', 'nombre' => 'IZTAPA', 'departamento_codigo' => '05'],
            ['codigo' => '0511', 'nombre' => 'PALÍN', 'departamento_codigo' => '05'],
            ['codigo' => '0512', 'nombre' => 'SAN VICENTE PACAYA', 'departamento_codigo' => '05'],
            ['codigo' => '0513', 'nombre' => 'NUEVA CONCEPCIÓN', 'departamento_codigo' => '05'],
            ['codigo' => '0514', 'nombre' => 'SIPACATE', 'departamento_codigo' => '05'],
            ['codigo' => '0599', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '05'],

            // 06 - Santa Rosa
            ['codigo' => '0601', 'nombre' => 'CUILAPA', 'departamento_codigo' => '06'],
            ['codigo' => '0602', 'nombre' => 'BARBERENA', 'departamento_codigo' => '06'],
            ['codigo' => '0603', 'nombre' => 'SANTA ROSA DE LIMA', 'departamento_codigo' => '06'],
            ['codigo' => '0604', 'nombre' => 'CASILLAS', 'departamento_codigo' => '06'],
            ['codigo' => '0605', 'nombre' => 'SAN RAFAEL LAS FLORES', 'departamento_codigo' => '06'],
            ['codigo' => '0606', 'nombre' => 'ORATORIO', 'departamento_codigo' => '06'],
            ['codigo' => '0607', 'nombre' => 'SAN JUAN TECUACO', 'departamento_codigo' => '06'],
            ['codigo' => '0608', 'nombre' => 'CHIQUIMULILLA', 'departamento_codigo' => '06'],
            ['codigo' => '0609', 'nombre' => 'TAXISCO', 'departamento_codigo' => '06'],
            ['codigo' => '0610', 'nombre' => 'SANTA MARÍA IXHUATÁN', 'departamento_codigo' => '06'],
            ['codigo' => '0611', 'nombre' => 'GUAZACAPÁN', 'departamento_codigo' => '06'],
            ['codigo' => '0612', 'nombre' => 'SANTA CRUZ NARANJO', 'departamento_codigo' => '06'],
            ['codigo' => '0613', 'nombre' => 'PUEBLO NUEVO VIÑAS', 'departamento_codigo' => '06'],
            ['codigo' => '0614', 'nombre' => 'NUEVA SANTA ROSA', 'departamento_codigo' => '06'],
            ['codigo' => '0699', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '06'],

            // 07 - Sololá
            ['codigo' => '0701', 'nombre' => 'SOLOLÁ', 'departamento_codigo' => '07'],
            ['codigo' => '0702', 'nombre' => 'SAN JOSÉ CHACAYÁ', 'departamento_codigo' => '07'],
            ['codigo' => '0703', 'nombre' => 'SANTA MARÍA VISITACIÓN', 'departamento_codigo' => '07'],
            ['codigo' => '0704', 'nombre' => 'SANTA LUCÍA UTATLÁN', 'departamento_codigo' => '07'],
            ['codigo' => '0705', 'nombre' => 'NAHUALÁ', 'departamento_codigo' => '07'],
            ['codigo' => '0706', 'nombre' => 'SANTA CATARINA IXTAHUACÁN', 'departamento_codigo' => '07'],
            ['codigo' => '0707', 'nombre' => 'SANTA CLARA LA LAGUNA', 'departamento_codigo' => '07'],
            ['codigo' => '0708', 'nombre' => 'CONCEPCIÓN', 'departamento_codigo' => '07'],
            ['codigo' => '0709', 'nombre' => 'SAN ANDRÉS SEMETABAJ', 'departamento_codigo' => '07'],
            ['codigo' => '0710', 'nombre' => 'PANAJACHEL', 'departamento_codigo' => '07'],
            ['codigo' => '0711', 'nombre' => 'SANTA CATARINA PALOPÓ', 'departamento_codigo' => '07'],
            ['codigo' => '0712', 'nombre' => 'SAN ANTONIO PALOPÓ', 'departamento_codigo' => '07'],
            ['codigo' => '0713', 'nombre' => 'SAN LUCAS TOLIMÁN', 'departamento_codigo' => '07'],
            ['codigo' => '0714', 'nombre' => 'SANTA CRUZ LA LAGUNA', 'departamento_codigo' => '07'],
            ['codigo' => '0715', 'nombre' => 'SAN PABLO LA LAGUNA', 'departamento_codigo' => '07'],
            ['codigo' => '0716', 'nombre' => 'SAN MARCOS LA LAGUNA', 'departamento_codigo' => '07'],
            ['codigo' => '0717', 'nombre' => 'SAN JUAN LA LAGUNA', 'departamento_codigo' => '07'],
            ['codigo' => '0718', 'nombre' => 'SAN PEDRO LA LAGUNA', 'departamento_codigo' => '07'],
            ['codigo' => '0719', 'nombre' => 'SANTIAGO ATITLÁN', 'departamento_codigo' => '07'],
            ['codigo' => '0799', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '07'],

            // 08 - Totonicapán
            ['codigo' => '0801', 'nombre' => 'TOTONICAPÁN', 'departamento_codigo' => '08'],
            ['codigo' => '0802', 'nombre' => 'SAN CRISTÓBAL TOTONICAPÁN', 'departamento_codigo' => '08'],
            ['codigo' => '0803', 'nombre' => 'SAN FRANCISCO EL ALTO', 'departamento_codigo' => '08'],
            ['codigo' => '0804', 'nombre' => 'SAN ANDRÉS XECUL', 'departamento_codigo' => '08'],
            ['codigo' => '0805', 'nombre' => 'MOMOSTENANGO', 'departamento_codigo' => '08'],
            ['codigo' => '0806', 'nombre' => 'SANTA MARÍA CHIQUIMULA', 'departamento_codigo' => '08'],
            ['codigo' => '0807', 'nombre' => 'SANTA LUCÍA LA REFORMA', 'departamento_codigo' => '08'],
            ['codigo' => '0808', 'nombre' => 'SAN BARTOLO AGUAS CALIENTES', 'departamento_codigo' => '08'],
            ['codigo' => '0899', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '08'],

            // 09 - Quetzaltenango
            ['codigo' => '0901', 'nombre' => 'QUETZALTENANGO', 'departamento_codigo' => '09'],
            ['codigo' => '0902', 'nombre' => 'SALCAJÁ', 'departamento_codigo' => '09'],
            ['codigo' => '0903', 'nombre' => 'OLINTEPEQUE', 'departamento_codigo' => '09'],
            ['codigo' => '0904', 'nombre' => 'SAN CARLOS SIJA', 'departamento_codigo' => '09'],
            ['codigo' => '0905', 'nombre' => 'SIBILIA', 'departamento_codigo' => '09'],
            ['codigo' => '0906', 'nombre' => 'CABRICÁN', 'departamento_codigo' => '09'],
            ['codigo' => '0907', 'nombre' => 'CAJOLÁ', 'departamento_codigo' => '09'],
            ['codigo' => '0908', 'nombre' => 'SAN MIGUEL SIGUILÁ', 'departamento_codigo' => '09'],
            ['codigo' => '0909', 'nombre' => 'SAN JUAN OSTUNCALCO', 'departamento_codigo' => '09'],
            ['codigo' => '0910', 'nombre' => 'SAN MATEO', 'departamento_codigo' => '09'],
            ['codigo' => '0911', 'nombre' => 'CONCEPCIÓN CHIQUIRICHAPA', 'departamento_codigo' => '09'],
            ['codigo' => '0912', 'nombre' => 'SAN MARTÍN SACATEPÉQUEZ', 'departamento_codigo' => '09'],
            ['codigo' => '0913', 'nombre' => 'ALMOLONGA', 'departamento_codigo' => '09'],
            ['codigo' => '0914', 'nombre' => 'CANTEL', 'departamento_codigo' => '09'],
            ['codigo' => '0915', 'nombre' => 'HUITÁN', 'departamento_codigo' => '09'],
            ['codigo' => '0916', 'nombre' => 'ZUNIL', 'departamento_codigo' => '09'],
            ['codigo' => '0917', 'nombre' => 'COLOMBA', 'departamento_codigo' => '09'],
            ['codigo' => '0918', 'nombre' => 'SAN FRANCISCO LA UNIÓN', 'departamento_codigo' => '09'],
            ['codigo' => '0919', 'nombre' => 'EL PALMAR', 'departamento_codigo' => '09'],
            ['codigo' => '0920', 'nombre' => 'COATEPEQUE', 'departamento_codigo' => '09'],
            ['codigo' => '0921', 'nombre' => 'GÉNOVA', 'departamento_codigo' => '09'],
            ['codigo' => '0922', 'nombre' => 'FLORES COSTA CUCA', 'departamento_codigo' => '09'],
            ['codigo' => '0923', 'nombre' => 'LA ESPERANZA', 'departamento_codigo' => '09'],
            ['codigo' => '0924', 'nombre' => 'PALESTINA DE LOS ALTOS', 'departamento_codigo' => '09'],
            ['codigo' => '0999', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '09'],

            // 10 - Suchitepéquez
            ['codigo' => '1001', 'nombre' => 'MAZATENANGO', 'departamento_codigo' => '10'],
            ['codigo' => '1002', 'nombre' => 'CUYOTENANGO', 'departamento_codigo' => '10'],
            ['codigo' => '1003', 'nombre' => 'SAN FRANCISCO ZAPOTITLÁN', 'departamento_codigo' => '10'],
            ['codigo' => '1004', 'nombre' => 'SAN BERNARDINO', 'departamento_codigo' => '10'],
            ['codigo' => '1005', 'nombre' => 'SAN JOSÉ EL ÍDOLO', 'departamento_codigo' => '10'],
            ['codigo' => '1006', 'nombre' => 'SANTO DOMINGO SUCHITEPÉQUEZ', 'departamento_codigo' => '10'],
            ['codigo' => '1007', 'nombre' => 'SAN LORENZO', 'departamento_codigo' => '10'],
            ['codigo' => '1008', 'nombre' => 'SAMAYAC', 'departamento_codigo' => '10'],
            ['codigo' => '1009', 'nombre' => 'SAN PABLO JOCOPILAS', 'departamento_codigo' => '10'],
            ['codigo' => '1010', 'nombre' => 'SAN ANTONIO SUCHITEPÉQUEZ', 'departamento_codigo' => '10'],
            ['codigo' => '1011', 'nombre' => 'SAN MIGUEL PANAN', 'departamento_codigo' => '10'],
            ['codigo' => '1012', 'nombre' => 'SAN GABRIEL', 'departamento_codigo' => '10'],
            ['codigo' => '1013', 'nombre' => 'CHICACAO', 'departamento_codigo' => '10'],
            ['codigo' => '1014', 'nombre' => 'PATULUL', 'departamento_codigo' => '10'],
            ['codigo' => '1015', 'nombre' => 'SANTA BÁRBARA', 'departamento_codigo' => '10'],
            ['codigo' => '1016', 'nombre' => 'SAN JUAN BAUTISTA', 'departamento_codigo' => '10'],
            ['codigo' => '1017', 'nombre' => 'SANTO TOMÁS LA UNIÓN', 'departamento_codigo' => '10'],
            ['codigo' => '1018', 'nombre' => 'ZUNILITO', 'departamento_codigo' => '10'],
            ['codigo' => '1019', 'nombre' => 'PUEBLO NUEVO', 'departamento_codigo' => '10'],
            ['codigo' => '1020', 'nombre' => 'RÍO BRAVO', 'departamento_codigo' => '10'],
            ['codigo' => '1021', 'nombre' => 'SAN JOSÉ LA MÁQUINA', 'departamento_codigo' => '10'],
            ['codigo' => '1099', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '10'],

            // 11 - Retalhuleu
            ['codigo' => '1101', 'nombre' => 'RETALHULEU', 'departamento_codigo' => '11'],
            ['codigo' => '1102', 'nombre' => 'SAN SEBASTIÁN', 'departamento_codigo' => '11'],
            ['codigo' => '1103', 'nombre' => 'SANTA CRUZ MULUÁ', 'departamento_codigo' => '11'],
            ['codigo' => '1104', 'nombre' => 'SAN MARTÍN ZAPOTITLÁN', 'departamento_codigo' => '11'],
            ['codigo' => '1105', 'nombre' => 'SAN FELIPE', 'departamento_codigo' => '11'],
            ['codigo' => '1106', 'nombre' => 'SAN ANDRÉS VILLA SECA', 'departamento_codigo' => '11'],
            ['codigo' => '1107', 'nombre' => 'CHAMPERICO', 'departamento_codigo' => '11'],
            ['codigo' => '1108', 'nombre' => 'NUEVO SAN CARLOS', 'departamento_codigo' => '11'],
            ['codigo' => '1109', 'nombre' => 'EL ASINTAL', 'departamento_codigo' => '11'],
            ['codigo' => '1199', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '11'],

            // 12 - San Marcos
            ['codigo' => '1201', 'nombre' => 'SAN MARCOS', 'departamento_codigo' => '12'],
            ['codigo' => '1202', 'nombre' => 'SAN  PEDRO SACATEPÉQUEZ', 'departamento_codigo' => '12'],
            ['codigo' => '1203', 'nombre' => 'SAN ANTONIO SACATEPÉQUEZ', 'departamento_codigo' => '12'],
            ['codigo' => '1204', 'nombre' => 'COMITANCILLO', 'departamento_codigo' => '12'],
            ['codigo' => '1205', 'nombre' => 'SAN MIGUEL IXTAHUACÁN', 'departamento_codigo' => '12'],
            ['codigo' => '1206', 'nombre' => 'CONCEPCIÓN TUTUAPA', 'departamento_codigo' => '12'],
            ['codigo' => '1207', 'nombre' => 'TACANÁ', 'departamento_codigo' => '12'],
            ['codigo' => '1208', 'nombre' => 'SIBINAL', 'departamento_codigo' => '12'],
            ['codigo' => '1209', 'nombre' => 'TAJUMULCO', 'departamento_codigo' => '12'],
            ['codigo' => '1210', 'nombre' => 'TEJUTLA', 'departamento_codigo' => '12'],
            ['codigo' => '1211', 'nombre' => 'SAN RAFAEL PIE DE LA CUESTA', 'departamento_codigo' => '12'],
            ['codigo' => '1212', 'nombre' => 'NUEVO PROGRESO', 'departamento_codigo' => '12'],
            ['codigo' => '1213', 'nombre' => 'EL TUMBADOR', 'departamento_codigo' => '12'],
            ['codigo' => '1214', 'nombre' => 'EL RODEO', 'departamento_codigo' => '12'],
            ['codigo' => '1215', 'nombre' => 'MALACATÁN', 'departamento_codigo' => '12'],
            ['codigo' => '1216', 'nombre' => 'CATARINA', 'departamento_codigo' => '12'],
            ['codigo' => '1217', 'nombre' => 'AYUTLA', 'departamento_codigo' => '12'],
            ['codigo' => '1218', 'nombre' => 'OCÓS', 'departamento_codigo' => '12'],
            ['codigo' => '1219', 'nombre' => 'SAN PABLO', 'departamento_codigo' => '12'],
            ['codigo' => '1220', 'nombre' => 'EL QUETZAL', 'departamento_codigo' => '12'],
            ['codigo' => '1221', 'nombre' => 'LA REFORMA', 'departamento_codigo' => '12'],
            ['codigo' => '1222', 'nombre' => 'PAJAPITA', 'departamento_codigo' => '12'],
            ['codigo' => '1223', 'nombre' => 'IXCHIGUÁN', 'departamento_codigo' => '12'],
            ['codigo' => '1224', 'nombre' => 'SAN JOSÉ OJETENAM', 'departamento_codigo' => '12'],
            ['codigo' => '1225', 'nombre' => 'SAN CRISTÓBAL CUCHO', 'departamento_codigo' => '12'],
            ['codigo' => '1226', 'nombre' => 'SIPACAPA', 'departamento_codigo' => '12'],
            ['codigo' => '1227', 'nombre' => 'ESQUIPULAS PALO GORDO', 'departamento_codigo' => '12'],
            ['codigo' => '1228', 'nombre' => 'RÍO BLANCO', 'departamento_codigo' => '12'],
            ['codigo' => '1229', 'nombre' => 'SAN LORENZO', 'departamento_codigo' => '12'],
            ['codigo' => '1230', 'nombre' => 'LA BLANCA', 'departamento_codigo' => '12'],
            ['codigo' => '1299', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '12'],

            // 13 - Huehuetenango
            ['codigo' => '1301', 'nombre' => 'HUEHUETENANGO', 'departamento_codigo' => '13'],
            ['codigo' => '1302', 'nombre' => 'CHIANTLA', 'departamento_codigo' => '13'],
            ['codigo' => '1303', 'nombre' => 'MALACATANCITO', 'departamento_codigo' => '13'],
            ['codigo' => '1304', 'nombre' => 'CUILCO', 'departamento_codigo' => '13'],
            ['codigo' => '1305', 'nombre' => 'NENTÓN', 'departamento_codigo' => '13'],
            ['codigo' => '1306', 'nombre' => 'SAN PEDRO NECTA', 'departamento_codigo' => '13'],
            ['codigo' => '1307', 'nombre' => 'JACALTENANGO', 'departamento_codigo' => '13'],
            ['codigo' => '1308', 'nombre' => 'SOLOMA', 'departamento_codigo' => '13'],
            ['codigo' => '1309', 'nombre' => 'SAN ILDEFONSO IXTAHUACÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1310', 'nombre' => 'SANTA BÁRBARA', 'departamento_codigo' => '13'],
            ['codigo' => '1311', 'nombre' => 'LA LIBERTAD', 'departamento_codigo' => '13'],
            ['codigo' => '1312', 'nombre' => 'LA DEMOCRACIA', 'departamento_codigo' => '13'],
            ['codigo' => '1313', 'nombre' => 'SAN MIGUEL ACATÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1314', 'nombre' => 'SAN RAFAEL LA INDEPENDENCIA', 'departamento_codigo' => '13'],
            ['codigo' => '1315', 'nombre' => 'TODOS SANTOS CUCHUMATÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1316', 'nombre' => 'SAN JUAN ATITÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1317', 'nombre' => 'SANTA EULALIA', 'departamento_codigo' => '13'],
            ['codigo' => '1318', 'nombre' => 'SAN MATEO IXTATÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1319', 'nombre' => 'COLOTENANGO', 'departamento_codigo' => '13'],
            ['codigo' => '1320', 'nombre' => 'SAN SEBASTIÁN HUEHUETENANGO', 'departamento_codigo' => '13'],
            ['codigo' => '1321', 'nombre' => 'TECTITÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1322', 'nombre' => 'CONCEPCIÓN HUISTA', 'departamento_codigo' => '13'],
            ['codigo' => '1323', 'nombre' => 'SAN JUAN IXCOY', 'departamento_codigo' => '13'],
            ['codigo' => '1324', 'nombre' => 'SAN ANTONIO HUISTA', 'departamento_codigo' => '13'],
            ['codigo' => '1325', 'nombre' => 'SAN SEBASTIÁN COATÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1326', 'nombre' => 'BARILLAS', 'departamento_codigo' => '13'],
            ['codigo' => '1327', 'nombre' => 'AGUACATÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1328', 'nombre' => 'SAN RAFAEL PÉTZAL', 'departamento_codigo' => '13'],
            ['codigo' => '1329', 'nombre' => 'SAN GASPAR IXCHIL', 'departamento_codigo' => '13'],
            ['codigo' => '1330', 'nombre' => 'SANTIAGO CHIMALTENANGO', 'departamento_codigo' => '13'],
            ['codigo' => '1331', 'nombre' => 'SANTA ANA HUISTA', 'departamento_codigo' => '13'],
            ['codigo' => '1332', 'nombre' => 'UNIÓN CANTINIL', 'departamento_codigo' => '13'],
            ['codigo' => '1333', 'nombre' => 'PETATÁN', 'departamento_codigo' => '13'],
            ['codigo' => '1399', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '13'],

            // 14 - Quiché
            ['codigo' => '1401', 'nombre' => 'SANTA CRUZ DEL QUICHE', 'departamento_codigo' => '14'],
            ['codigo' => '1402', 'nombre' => 'CHICHÉ', 'departamento_codigo' => '14'],
            ['codigo' => '1403', 'nombre' => 'CHINIQUE', 'departamento_codigo' => '14'],
            ['codigo' => '1404', 'nombre' => 'ZACUALPA', 'departamento_codigo' => '14'],
            ['codigo' => '1405', 'nombre' => 'CHAJUL', 'departamento_codigo' => '14'],
            ['codigo' => '1406', 'nombre' => 'CHICHICASTENANGO', 'departamento_codigo' => '14'],
            ['codigo' => '1407', 'nombre' => 'PATZITÉ', 'departamento_codigo' => '14'],
            ['codigo' => '1408', 'nombre' => 'SAN ANTONIO ILOTENANGO', 'departamento_codigo' => '14'],
            ['codigo' => '1409', 'nombre' => 'SAN PEDRO JOCOPILAS', 'departamento_codigo' => '14'],
            ['codigo' => '1410', 'nombre' => 'CUNÉN', 'departamento_codigo' => '14'],
            ['codigo' => '1411', 'nombre' => 'SAN JUAN COTZAL', 'departamento_codigo' => '14'],
            ['codigo' => '1412', 'nombre' => 'JOYABAJ', 'departamento_codigo' => '14'],
            ['codigo' => '1413', 'nombre' => 'NEBAJ', 'departamento_codigo' => '14'],
            ['codigo' => '1414', 'nombre' => 'SAN ANDRÉS SAJCABAJÁ', 'departamento_codigo' => '14'],
            ['codigo' => '1415', 'nombre' => 'USPANTÁN', 'departamento_codigo' => '14'],
            ['codigo' => '1416', 'nombre' => 'SACAPULAS', 'departamento_codigo' => '14'],
            ['codigo' => '1417', 'nombre' => 'SAN BARTOLOMÉ JOCOTENANGO', 'departamento_codigo' => '14'],
            ['codigo' => '1418', 'nombre' => 'CANILLÁ', 'departamento_codigo' => '14'],
            ['codigo' => '1419', 'nombre' => 'CHICAMÁN', 'departamento_codigo' => '14'],
            ['codigo' => '1420', 'nombre' => 'IXCÁN', 'departamento_codigo' => '14'],
            ['codigo' => '1421', 'nombre' => 'PACHALUM', 'departamento_codigo' => '14'],
            ['codigo' => '1499', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '14'],

            // 15 - Baja Verapaz
            ['codigo' => '1501', 'nombre' => 'SALAMÁ', 'departamento_codigo' => '15'],
            ['codigo' => '1502', 'nombre' => 'SAN MIGUEL CHICAJ', 'departamento_codigo' => '15'],
            ['codigo' => '1503', 'nombre' => 'RABINAL', 'departamento_codigo' => '15'],
            ['codigo' => '1504', 'nombre' => 'CUBULCO', 'departamento_codigo' => '15'],
            ['codigo' => '1505', 'nombre' => 'GRANADOS', 'departamento_codigo' => '15'],
            ['codigo' => '1506', 'nombre' => 'EL CHOL', 'departamento_codigo' => '15'],
            ['codigo' => '1507', 'nombre' => 'SAN JERÓNIMO', 'departamento_codigo' => '15'],
            ['codigo' => '1508', 'nombre' => 'PURULHÁ', 'departamento_codigo' => '15'],
            ['codigo' => '1599', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '15'],

            // 16 - Alta Verapaz
            ['codigo' => '1601', 'nombre' => 'COBÁN', 'departamento_codigo' => '16'],
            ['codigo' => '1602', 'nombre' => 'SANTA CRUZ VERAPAZ', 'departamento_codigo' => '16'],
            ['codigo' => '1603', 'nombre' => 'SAN CRISTÓBAL VERAPAZ', 'departamento_codigo' => '16'],
            ['codigo' => '1604', 'nombre' => 'TACTIC', 'departamento_codigo' => '16'],
            ['codigo' => '1605', 'nombre' => 'TAMAHÚ', 'departamento_codigo' => '16'],
            ['codigo' => '1606', 'nombre' => 'TUCURÚ', 'departamento_codigo' => '16'],
            ['codigo' => '1607', 'nombre' => 'PANZÓS', 'departamento_codigo' => '16'],
            ['codigo' => '1608', 'nombre' => 'SENAHÚ', 'departamento_codigo' => '16'],
            ['codigo' => '1609', 'nombre' => 'SAN PEDRO CARCHÁ', 'departamento_codigo' => '16'],
            ['codigo' => '1610', 'nombre' => 'SAN JUAN CHAMELCO', 'departamento_codigo' => '16'],
            ['codigo' => '1611', 'nombre' => 'LANQUÍN', 'departamento_codigo' => '16'],
            ['codigo' => '1612', 'nombre' => 'CAHABÓN', 'departamento_codigo' => '16'],
            ['codigo' => '1613', 'nombre' => 'CHISEC', 'departamento_codigo' => '16'],
            ['codigo' => '1614', 'nombre' => 'CHAHAL', 'departamento_codigo' => '16'],
            ['codigo' => '1615', 'nombre' => 'FRAY BARTOLOMÉ DE LAS CASAS', 'departamento_codigo' => '16'],
            ['codigo' => '1616', 'nombre' => 'SANTA CATALINA LA TINTA', 'departamento_codigo' => '16'],
            ['codigo' => '1617', 'nombre' => 'RAXRUHÁ', 'departamento_codigo' => '16'],
            ['codigo' => '1699', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '16'],

            // 17 - Petén
            ['codigo' => '1701', 'nombre' => 'FLORES', 'departamento_codigo' => '17'],
            ['codigo' => '1702', 'nombre' => 'SAN JOSÉ', 'departamento_codigo' => '17'],
            ['codigo' => '1703', 'nombre' => 'SAN BENITO', 'departamento_codigo' => '17'],
            ['codigo' => '1704', 'nombre' => 'SAN ANDRÉS', 'departamento_codigo' => '17'],
            ['codigo' => '1705', 'nombre' => 'LA LIBERTAD', 'departamento_codigo' => '17'],
            ['codigo' => '1706', 'nombre' => 'SAN FRANCISCO', 'departamento_codigo' => '17'],
            ['codigo' => '1707', 'nombre' => 'SANTA ANA', 'departamento_codigo' => '17'],
            ['codigo' => '1708', 'nombre' => 'DOLORES', 'departamento_codigo' => '17'],
            ['codigo' => '1709', 'nombre' => 'SAN LUIS', 'departamento_codigo' => '17'],
            ['codigo' => '1710', 'nombre' => 'SAYAXCHÉ', 'departamento_codigo' => '17'],
            ['codigo' => '1711', 'nombre' => 'MELCHOR DE MENCOS', 'departamento_codigo' => '17'],
            ['codigo' => '1712', 'nombre' => 'POPTÚN', 'departamento_codigo' => '17'],
            ['codigo' => '1713', 'nombre' => 'LAS CRUCES', 'departamento_codigo' => '17'],
            ['codigo' => '1714', 'nombre' => 'EL CHAL', 'departamento_codigo' => '17'],
            ['codigo' => '1799', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '17'],

            // 18 - Izabal
            ['codigo' => '1801', 'nombre' => 'PUERTO BARRIOS', 'departamento_codigo' => '18'],
            ['codigo' => '1802', 'nombre' => 'LIVINGSTON', 'departamento_codigo' => '18'],
            ['codigo' => '1803', 'nombre' => 'EL ESTOR', 'departamento_codigo' => '18'],
            ['codigo' => '1804', 'nombre' => 'MORALES', 'departamento_codigo' => '18'],
            ['codigo' => '1805', 'nombre' => 'LOS AMATES', 'departamento_codigo' => '18'],
            ['codigo' => '1899', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '18'],

            // 19 - Zacapa
            ['codigo' => '1901', 'nombre' => 'ZACAPA', 'departamento_codigo' => '19'],
            ['codigo' => '1902', 'nombre' => 'ESTANZUELA', 'departamento_codigo' => '19'],
            ['codigo' => '1903', 'nombre' => 'RÍO HONDO', 'departamento_codigo' => '19'],
            ['codigo' => '1904', 'nombre' => 'GUALÁN', 'departamento_codigo' => '19'],
            ['codigo' => '1905', 'nombre' => 'TECULUTÁN', 'departamento_codigo' => '19'],
            ['codigo' => '1906', 'nombre' => 'USUMATLÁN', 'departamento_codigo' => '19'],
            ['codigo' => '1907', 'nombre' => 'CABAÑAS', 'departamento_codigo' => '19'],
            ['codigo' => '1908', 'nombre' => 'SAN DIEGO', 'departamento_codigo' => '19'],
            ['codigo' => '1909', 'nombre' => 'LA UNIÓN', 'departamento_codigo' => '19'],
            ['codigo' => '1910', 'nombre' => 'HUITÉ', 'departamento_codigo' => '19'],
            ['codigo' => '1911', 'nombre' => 'SAN JORGE', 'departamento_codigo' => '19'],
            ['codigo' => '1999', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '19'],

            // 20 - Chiquimula
            ['codigo' => '2001', 'nombre' => 'CHIQUIMULA', 'departamento_codigo' => '20'],
            ['codigo' => '2002', 'nombre' => 'SAN JOSÉ LA ARADA', 'departamento_codigo' => '20'],
            ['codigo' => '2003', 'nombre' => 'SAN JUAN ERMITA', 'departamento_codigo' => '20'],
            ['codigo' => '2004', 'nombre' => 'JOCOTÁN', 'departamento_codigo' => '20'],
            ['codigo' => '2005', 'nombre' => 'CAMOTÁN', 'departamento_codigo' => '20'],
            ['codigo' => '2006', 'nombre' => 'OLOPA', 'departamento_codigo' => '20'],
            ['codigo' => '2007', 'nombre' => 'ESQUIPULAS', 'departamento_codigo' => '20'],
            ['codigo' => '2008', 'nombre' => 'CONCEPCIÓN LAS MINAS', 'departamento_codigo' => '20'],
            ['codigo' => '2009', 'nombre' => 'QUEZALTEPEQUE', 'departamento_codigo' => '20'],
            ['codigo' => '2010', 'nombre' => 'SAN JACINTO', 'departamento_codigo' => '20'],
            ['codigo' => '2011', 'nombre' => 'IPALA', 'departamento_codigo' => '20'],
            ['codigo' => '2099', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '20'],

            // 21 - Jalapa
            ['codigo' => '2101', 'nombre' => 'JALAPA', 'departamento_codigo' => '21'],
            ['codigo' => '2102', 'nombre' => 'SAN PEDRO PINULA', 'departamento_codigo' => '21'],
            ['codigo' => '2103', 'nombre' => 'SAN LUIS JILOTEPEQUE', 'departamento_codigo' => '21'],
            ['codigo' => '2104', 'nombre' => 'SAN MANUEL CHAPARRÓN', 'departamento_codigo' => '21'],
            ['codigo' => '2105', 'nombre' => 'SAN CARLOS ALZATATE', 'departamento_codigo' => '21'],
            ['codigo' => '2106', 'nombre' => 'MONJAS', 'departamento_codigo' => '21'],
            ['codigo' => '2107', 'nombre' => 'MATAQUESCUINTLA', 'departamento_codigo' => '21'],
            ['codigo' => '2199', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '21'],

            // 22 - Jutiapa
            ['codigo' => '2201', 'nombre' => 'JUTIAPA', 'departamento_codigo' => '22'],
            ['codigo' => '2202', 'nombre' => 'EL PROGRESO', 'departamento_codigo' => '22'],
            ['codigo' => '2203', 'nombre' => 'SANTA CATARINA MITA', 'departamento_codigo' => '22'],
            ['codigo' => '2204', 'nombre' => 'AGUA BLANCA', 'departamento_codigo' => '22'],
            ['codigo' => '2205', 'nombre' => 'ASUNCIÓN MITA', 'departamento_codigo' => '22'],
            ['codigo' => '2206', 'nombre' => 'YUPILTEPEQUE', 'departamento_codigo' => '22'],
            ['codigo' => '2207', 'nombre' => 'ATESCATEMPA', 'departamento_codigo' => '22'],
            ['codigo' => '2208', 'nombre' => 'JEREZ', 'departamento_codigo' => '22'],
            ['codigo' => '2209', 'nombre' => 'EL ADELANTO', 'departamento_codigo' => '22'],
            ['codigo' => '2210', 'nombre' => 'ZAPOTITLÁN', 'departamento_codigo' => '22'],
            ['codigo' => '2211', 'nombre' => 'COMAPA', 'departamento_codigo' => '22'],
            ['codigo' => '2212', 'nombre' => 'JALPATAGUA', 'departamento_codigo' => '22'],
            ['codigo' => '2213', 'nombre' => 'CONGUACO', 'departamento_codigo' => '22'],
            ['codigo' => '2214', 'nombre' => 'MOYUTA', 'departamento_codigo' => '22'],
            ['codigo' => '2215', 'nombre' => 'PASACO', 'departamento_codigo' => '22'],
            ['codigo' => '2216', 'nombre' => 'SAN JOSÉ ACATEMPA', 'departamento_codigo' => '22'],
            ['codigo' => '2217', 'nombre' => 'QUESADA', 'departamento_codigo' => '22'],
            ['codigo' => '2299', 'nombre' => 'MULTIMUNICIPAL', 'departamento_codigo' => '22'],
        ];

        foreach ($municipios as $mun) {
            $departamento = Departamento::where('codigo', $mun['departamento_codigo'])->first();
            if ($departamento) {
                Municipio::create([
                    'codigo' => $mun['codigo'],
                    'nombre' => $mun['nombre'],
                    'departamento_id' => $departamento->id,
                ]);
            }
        }
    }
}
