<?php

namespace Database\Seeders;

use App\Models\Option;
use Illuminate\Database\Seeder;

class OptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        deshabilitaLlavesForaneas();

        \DB::table('options')->delete();

        \DB::table('options')->insert(array (
            0 =>
            array (
                'id' => 1,
                'option_id' => NULL,
                'nombre' => 'Panel de Control',
                'ruta' => 'admin.dashboard',
                'descripcion' => NULL,
                'icono_l' => 'text-primary fa-tachometer-alt',
                'icono_r' => NULL,
                'orden' => 0,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2020-03-06 14:09:05',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'option_id' => NULL,
                'nombre' => 'Solicitudes de Compra',
                'ruta' => 'x',
                'descripcion' => 'x',
                'icono_l' => 'fa-clipboard-list',
                'icono_r' => NULL,
                'orden' => 1,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2025-04-15 09:12:39',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'option_id' => 2,
                'nombre' => 'Nueva Solicitud de Compra',
                'ruta' => 'compra.solicitudes.nueva',
                'descripcion' => 'x',
                'icono_l' => 'fa-file-signature',
                'icono_r' => NULL,
                'orden' => 2,
                'color' => 'danger',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2025-04-15 09:13:34',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'option_id' => 2,
                'nombre' => 'Mis Solicitudes de Compras',
                'ruta' => 'compra.solicitudes.usuario',
                'descripcion' => NULL,
                'icono_l' => 'fa-shopping-cart',
                'icono_r' => NULL,
                'orden' => 3,
                'color' => 'warning',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2025-06-27 11:48:40',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'option_id' => 2,
                'nombre' => 'Buscar Solicitud de compra',
                'ruta' => 'compra.solicitudes.index',
                'descripcion' => 'x',
                'icono_l' => 'fa-search',
                'icono_r' => NULL,
                'orden' => 5,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2025-04-15 09:37:37',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'option_id' => 2,
                'nombre' => 'Consolidar Solicitudes',
                'ruta' => 'compra.solicitudes.consolidar',
                'descripcion' => NULL,
                'icono_l' => 'fa-check',
                'icono_r' => NULL,
                'orden' => 4,
                'color' => 'success',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2025-06-27 11:25:30',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'option_id' => NULL,
                'nombre' => 'Ingreso de Almacén',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-shopping-cart',
                'icono_r' => 'fa-angle-left',
                'orden' => 6,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'option_id' => 7,
                'nombre' => 'Nuevo Ingreso Almacén',
                'ruta' => 'compras.create',
                'descripcion' => NULL,
                'icono_l' => 'fa-cart-arrow-down',
                'icono_r' => NULL,
                'orden' => 0,
                'color' => '0',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2017-04-13 22:39:13',
                'updated_at' => '2025-08-25 15:28:18',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'option_id' => 7,
                'nombre' => 'Proveedores',
                'ruta' => 'proveedores.index',
                'descripcion' => 'Administración de proveedores',
                'icono_l' => 'fa-user-tie',
                'icono_r' => NULL,
                'orden' => 5,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-25 15:28:02',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'option_id' => 7,
                'nombre' => 'Buscar Ingresos a Almacén',
                'ruta' => 'compras.index',
                'descripcion' => 'Ingresos de artículos a inventario',
                'icono_l' => 'fa-search',
                'icono_r' => NULL,
                'orden' => 4,
                'color' => 'success',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-25 15:28:02',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'option_id' => NULL,
                'nombre' => 'Requisicion almacen',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-dolly-flatbed',
                'icono_r' => 'fa-angle-left',
                'orden' => 10,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-07-30 23:17:58',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'option_id' => 11,
                'nombre' => 'Nueva Requisición almacen',
                'ruta' => 'nueva.solicitud.almacen',
                'descripcion' => NULL,
                'icono_l' => 'fa-plus-square',
                'icono_r' => NULL,
                'orden' => 11,
                'color' => 'danger',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2018-07-30 23:19:08',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'option_id' => 11,
                'nombre' => 'Mis Requisiciones almacen',
                'ruta' => 'solicitudes.usuario',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-contract',
                'icono_r' => NULL,
                'orden' => 13,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-07-31 00:19:54',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'option_id' => 11,
                'nombre' => 'Autorizar Requisición almacen',
                'ruta' => 'solicitudes.autorizar',
                'descripcion' => NULL,
                'icono_l' => 'fa-stamp',
                'icono_r' => NULL,
                'orden' => 14,
                'color' => 'info',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-08-05 10:49:49',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'option_id' => 11,
                'nombre' => 'Aprobar Reqisición almacen',
                'ruta' => 'solicitudes.aprobar',
                'descripcion' => NULL,
                'icono_l' => 'fa-stamp',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-08-06 08:57:05',
                'updated_at' => '2025-08-25 11:55:50',
                'deleted_at' => '2025-08-25 11:55:50',
            ),
            15 =>
            array (
                'id' => 16,
                'option_id' => 11,
                'nombre' => 'Despachar Requisición almacen',
                'ruta' => 'solicitudes.despachar',
                'descripcion' => NULL,
                'icono_l' => 'fa-dolly',
                'icono_r' => NULL,
                'orden' => 16,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-07-31 00:16:45',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'option_id' => 11,
                'nombre' => 'Buscar Requisición almacen',
                'ruta' => 'solicitudes.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-search',
                'icono_r' => NULL,
                'orden' => 12,
                'color' => 'danger',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2018-07-31 00:32:26',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'option_id' => 11,
                'nombre' => 'Usuarios despachan ',
                'ruta' => 'user.despacha.user',
                'descripcion' => NULL,
                'icono_l' => 'fa-people-carry',
                'icono_r' => NULL,
                'orden' => 17,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-08-08 02:28:11',
                'updated_at' => '2025-08-25 11:55:40',
                'deleted_at' => '2025-08-25 11:55:40',
            ),
            18 =>
            array (
                'id' => 19,
                'option_id' => NULL,
                'nombre' => 'Insumos',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-barcode',
                'icono_r' => 'fa-angle-left',
                'orden' => 22,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2019-07-01 22:29:53',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'option_id' => 19,
                'nombre' => 'Nuevo Insumo',
                'ruta' => 'items.nuevo',
                'descripcion' => NULL,
                'icono_l' => 'fa-plus',
                'icono_r' => NULL,
                'orden' => 24,
                'color' => 'info',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2020-03-22 14:53:43',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'option_id' => 19,
                'nombre' => 'Buscar Insumos',
                'ruta' => 'items.index',
                'descripcion' => 'Administración de los artículos',
                'icono_l' => 'fa-barcode',
                'icono_r' => NULL,
                'orden' => 23,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'option_id' => 19,
                'nombre' => 'Categorías',
                'ruta' => 'itemCategorias.index',
                'descripcion' => 'Administración de las categorías de los articulos',
                'icono_l' => 'fa-folder',
                'icono_r' => NULL,
                'orden' => 30,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'option_id' => 19,
                'nombre' => 'Unidades de medida',
                'ruta' => 'unimeds.index',
                'descripcion' => 'Administración de las unidades de medida',
                'icono_l' => 'fa-balance-scale',
                'icono_r' => NULL,
                'orden' => 31,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'option_id' => 19,
                'nombre' => 'Marcas',
                'ruta' => 'marcas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tags',
                'icono_r' => NULL,
                'orden' => 29,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-05-19 23:20:31',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'option_id' => 19,
                'nombre' => 'Importar Excel',
                'ruta' => 'items.importar',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-import',
                'icono_r' => NULL,
                'orden' => 26,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2020-10-15 15:25:15',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'option_id' => 19,
                'nombre' => 'Traslado entre unidades',
                'ruta' => 'itemTraslados.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-balance-scale-left',
                'icono_r' => NULL,
                'orden' => 2,
                'color' => 'info',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-03-20 23:14:39',
                'updated_at' => '2025-07-01 09:51:11',
                'deleted_at' => '2025-07-01 09:51:11',
            ),
            26 =>
            array (
                'id' => 27,
                'option_id' => 19,
                'nombre' => 'Stock crítico',
                'ruta' => 'stock.critico',
                'descripcion' => NULL,
                'icono_l' => 'fa-exclamation-triangle',
                'icono_r' => NULL,
                'orden' => 27,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-09-09 19:53:29',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'option_id' => 19,
                'nombre' => 'Renglones',
                'ruta' => 'renglones.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-list',
                'icono_r' => NULL,
                'orden' => 28,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2023-03-22 14:39:59',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'option_id' => 19,
                'nombre' => 'Magnitud U/M',
                'ruta' => 'magnitudes.index',
                'descripcion' => 'Magnitudes unidades de medida',
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 25,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-07-28 16:26:22',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'option_id' => NULL,
                'nombre' => 'Inventarios',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-book',
                'icono_r' => NULL,
                'orden' => 33,
                'color' => 'info',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-08-29 16:56:26',
                'updated_at' => '2025-07-04 08:44:43',
                'deleted_at' => '2025-07-04 08:44:43',
            ),
            30 =>
            array (
                'id' => 31,
                'option_id' => 30,
                'nombre' => 'Activos fijos',
                'ruta' => 'activos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-computer',
                'icono_r' => NULL,
                'orden' => 34,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-08-29 22:14:51',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'option_id' => 30,
                'nombre' => 'Tarjeta de responsabilidad',
                'ruta' => 'activoTarjetas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-address-book',
                'icono_r' => NULL,
                'orden' => 35,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-08-29 16:58:20',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'option_id' => 30,
                'nombre' => 'Ingreso de código de inventario 1h',
                'ruta' => 'inventario.1h',
                'descripcion' => NULL,
                'icono_l' => 'fa-hashtag',
                'icono_r' => NULL,
                'orden' => 37,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-08-29 17:01:47',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'option_id' => 30,
                'nombre' => 'Solicitud de cargo o descargo de bienes',
                'ruta' => 'activoSolicitudes.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-contract',
                'icono_r' => NULL,
                'orden' => 38,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-08-29 17:03:40',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'option_id' => 30,
                'nombre' => 'Reporte Bienes por unidad',
                'ruta' => 'reporte.bienes.unidad',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 39,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-08-29 17:04:35',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'option_id' => 30,
                'nombre' => 'Importar Excel',
                'ruta' => 'activos.importar',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-import',
                'icono_r' => NULL,
                'orden' => 36,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-09-08 15:38:36',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'option_id' => NULL,
                'nombre' => 'Recursos Humanos',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-users',
                'icono_r' => NULL,
                'orden' => 41,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-12-08 08:47:18',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'option_id' => 37,
                'nombre' => 'Unidades / Dependencia',
                'ruta' => 'rrhhUnidades.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-house-laptop',
                'icono_r' => NULL,
                'orden' => 42,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-12-27 20:44:34',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'option_id' => 37,
                'nombre' => 'Colaboradores',
                'ruta' => 'colaboradores.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-user-tie',
                'icono_r' => NULL,
                'orden' => 42,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-12-08 08:49:00',
                'updated_at' => '2025-07-01 09:51:59',
                'deleted_at' => '2025-07-01 09:51:59',
            ),
            39 =>
            array (
                'id' => 40,
                'option_id' => NULL,
                'nombre' => 'Consumo',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-arrow-down',
                'icono_r' => NULL,
                'orden' => 18,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2022-12-27 11:23:53',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'option_id' => 40,
                'nombre' => 'Mis consumos',
                'ruta' => 'consumos.usuario',
                'descripcion' => NULL,
                'icono_l' => 'fa-list',
                'icono_r' => NULL,
                'orden' => 20,
                'color' => 'primary',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2022-12-27 11:24:18',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'option_id' => 40,
                'nombre' => 'Buscar consumo',
                'ruta' => 'consumos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-search',
                'icono_r' => NULL,
                'orden' => 21,
                'color' => 'success',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2022-12-27 11:24:44',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'option_id' => 40,
                'nombre' => 'Nuevo consumo',
                'ruta' => 'consumos.create',
                'descripcion' => NULL,
                'icono_l' => 'fa-plus',
                'icono_r' => NULL,
                'orden' => 19,
                'color' => 'danger',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2022-12-27 11:25:26',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'option_id' => NULL,
                'nombre' => 'Developer',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-code',
                'icono_r' => NULL,
                'orden' => 43,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 1,
                'created_at' => '2023-01-10 21:28:35',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'option_id' => 44,
                'nombre' => 'Menu',
                'ruta' => 'dev.options.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-list',
                'icono_r' => NULL,
                'orden' => 45,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 1,
                'created_at' => '2023-01-10 21:29:18',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'option_id' => 44,
                'nombre' => 'Prueba API\'S',
                'ruta' => 'dev.prueba.api',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 46,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 1,
                'created_at' => '2023-01-10 21:33:30',
                'updated_at' => '2025-08-20 20:54:14',
                'deleted_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'option_id' => 44,
                'nombre' => 'Configuraciones',
                'ruta' => 'dev.configurations.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-cogs',
                'icono_r' => NULL,
                'orden' => 47,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 1,
                'created_at' => '2023-01-10 21:34:04',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'option_id' => 44,
                'nombre' => 'Permisos',
                'ruta' => 'permissions.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-key',
                'icono_r' => NULL,
                'orden' => 44,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 1,
                'created_at' => '2020-03-13 14:55:36',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'option_id' => 44,
                'nombre' => 'Logs',
                'ruta' => 'dev.logs',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 48,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2023-01-27 11:15:32',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'option_id' => NULL,
                'nombre' => 'Admin',
                'ruta' => 'x',
                'descripcion' => 'Opciones de administración',
                'icono_l' => 'fa-folder',
                'icono_r' => 'fa-angle-left',
                'orden' => 37,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'option_id' => 50,
                'nombre' => 'Usuarios',
                'ruta' => 'users.index',
                'descripcion' => 'Administración de usuarios',
                'icono_l' => 'fa-users',
                'icono_r' => NULL,
                'orden' => 38,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'option_id' => 50,
                'nombre' => 'Roles',
                'ruta' => 'roles.index',
                'descripcion' => 'Administración de los roles de los usuarios',
                'icono_l' => 'fa-user-tag',
                'icono_r' => NULL,
                'orden' => 39,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'option_id' => 50,
                'nombre' => 'Configuraciones',
                'ruta' => 'profile.business',
                'descripcion' => NULL,
                'icono_l' => 'fa-cogs',
                'icono_r' => NULL,
                'orden' => 40,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2017-05-21 14:36:26',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'option_id' => NULL,
                'nombre' => 'Reportes',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'text-purple fa-chart-line',
                'icono_r' => 'fa-angle-left',
                'orden' => 32,
                'color' => 'warning',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-01-30 21:17:33',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'option_id' => 54,
                'nombre' => 'Stock',
                'ruta' => 'reportes.stock',
                'descripcion' => NULL,
                'icono_l' => 'fa fa-boxes',
                'icono_r' => NULL,
                'orden' => 34,
                'color' => 'primary',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-09-29 17:39:32',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'option_id' => 54,
                'nombre' => 'Kardex',
                'ruta' => 'reportes.kardex',
                'descripcion' => NULL,
                'icono_l' => 'fa-clipboard-list',
                'icono_r' => NULL,
                'orden' => 35,
                'color' => 'danger',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2018-02-06 18:52:48',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'option_id' => 54,
                'nombre' => 'Artículos A Vencer',
                'ruta' => 'reportes.items.vencen',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 36,
                'color' => 'success',
                'recursos' => 1,
                'dev' => 0,
                'created_at' => '2020-03-25 19:35:47',
                'updated_at' => '2025-08-22 14:40:24',
                'deleted_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'option_id' => 54,
                'nombre' => 'Libro Almacen',
                'ruta' => 'compras.libro.almacen',
                'descripcion' => NULL,
                'icono_l' => 'fa-book',
                'icono_r' => NULL,
                'orden' => 33,
                'color' => 'info',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2022-12-20 23:52:04',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'option_id' => NULL,
                'nombre' => 'Catálogos',
                'ruta' => 'x',
                'descripcion' => 'Administrar Catalogos',
                'icono_l' => 'fa-list',
                'icono_r' => NULL,
                'orden' => 50,
                'color' => 'info',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2025-08-20 20:53:57',
                'updated_at' => '2025-08-22 14:40:59',
                'deleted_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'option_id' => 59,
                'nombre' => 'Tipo Adquisición',
                'ruta' => 'compra.requisiciones.tipo-adquisiciones.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 51,
                'color' => 'info',
                'recursos' => 0,
                'dev' => 1,
                'created_at' => '2025-08-20 20:55:02',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'option_id' => 59,
                'nombre' => 'Requisición Compra Estados',
                'ruta' => 'compra.requisiciones.estados.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 52,
                'color' => 'primary',
                'recursos' => 0,
                'dev' => 1,
                'created_at' => '2025-08-20 20:57:27',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'option_id' => 59,
                'nombre' => 'Tipo Concursos Compra',
                'ruta' => 'compra.requisiciones.tipo-concursos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 53,
                'color' => 'danger',
                'recursos' => 0,
                'dev' => 1,
                'created_at' => '2025-08-20 21:05:57',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'option_id' => 59,
                'nombre' => 'Solicitud Compra Estados',
                'ruta' => 'compra.solicitudes.estados.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 54,
                'color' => 'primary',
                'recursos' => 0,
                'dev' => 1,
                'created_at' => '2025-08-20 21:16:08',
                'updated_at' => '2025-08-22 14:40:59',
                'deleted_at' => NULL,
            ),
            63 =>
            array (
                'id' => 64,
                'option_id' => 59,
                'nombre' => 'Compra Bandejas',
                'ruta' => 'compra.bandejas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 55,
                'color' => 'info',
                'recursos' => 0,
                'dev' => 1,
                'created_at' => '2025-08-20 21:22:28',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            64 =>
            array (
                'id' => 66,
                'option_id' => NULL,
                'nombre' => 'Prueba de firma electrónica',
                'ruta' => 'pruebas.firma.electronica',
                'descripcion' => NULL,
                'icono_l' => 'fa-signature',
                'icono_r' => NULL,
                'orden' => 49,
                'color' => 'info',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2025-08-22 14:40:50',
                'updated_at' => '2025-08-24 23:48:38',
                'deleted_at' => NULL,
            ),
            65 =>
            array (
                'id' => 67,
                'option_id' => 7,
                'nombre' => 'Operar ingreso',
                'ruta' => 'bandejas.compras1h.operador',
                'descripcion' => NULL,
                'icono_l' => 'fas fa-clipboard-check',
                'icono_r' => NULL,
                'orden' => 1,
                'color' => '0',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2025-08-25 15:25:47',
                'updated_at' => '2025-08-25 15:31:43',
                'deleted_at' => NULL,
            ),
            66 =>
            array (
                'id' => 68,
                'option_id' => 7,
                'nombre' => 'Aprobar Ingreso',
                'ruta' => 'bandejas.compras1h.aprobador',
                'descripcion' => NULL,
                'icono_l' => 'fas fa-user-shield',
                'icono_r' => NULL,
                'orden' => 2,
                'color' => '0',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2025-08-25 15:26:54',
                'updated_at' => '2025-08-25 15:33:52',
                'deleted_at' => NULL,
            ),
            67 =>
            array (
                'id' => 69,
                'option_id' => 7,
                'nombre' => 'Autorizar ingreso',
                'ruta' => 'bandejas.compras1h.autorizador',
                'descripcion' => NULL,
                'icono_l' => 'fa-stamp',
                'icono_r' => NULL,
                'orden' => 3,
                'color' => '0',
                'recursos' => 0,
                'dev' => 0,
                'created_at' => '2025-08-25 15:27:34',
                'updated_at' => '2025-08-25 15:33:43',
                'deleted_at' => NULL,
            ),
        ));

        $this->generarColores();


    }

    public function generarColores()
    {

        $opciones = Option::all();
        $colores =[
            'primary',
//            'secondary',
            'success',
            'info',
            'warning',
            'danger',
        ];

        foreach ($opciones as $key => $opcion) {
            $colorAleatorio = $colores[array_rand($colores)];
            $opcion->color = $colorAleatorio;
            $opcion->save();
        }

    }

}
