<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::statement('SET FOREIGN_KEY_CHECKS=0');

        \DB::table('options')->delete();

        \DB::table('options')->insert(array (
            0 =>
            array (
                'color' => 'bg-primary',
                'created_at' => '2020-03-06 14:09:05',
                'deleted_at' => '2022-09-01 00:10:52',
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'text-primary fa-tachometer-alt',
                'icono_r' => NULL,
                'id' => 1,
                'nombre' => 'Panel de Control',
                'option_id' => NULL,
                'orden' => 0,
                'ruta' => 'dashboard',
                'updated_at' => '2020-03-13 15:01:02',
            ),
            1 =>
            array (
                'color' => 'bg-purple',
                'created_at' => '2017-04-15 22:38:52',
                'deleted_at' => '2022-12-08 08:45:43',
                'descripcion' => 'Realizar nueva compra',
                'dev' => 0,
                'icono_l' => 'fas fa-solar-panel text-success',
                'icono_r' => NULL,
                'id' => 2,
                'nombre' => 'Ingreso Compra',
                'option_id' => NULL,
                'orden' => 1,
                'ruta' => 'compras.create',
                'updated_at' => '2022-12-08 08:45:43',
            ),
            2 =>
            array (
                'color' => 'bg-purple',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-shopping-cart',
                'icono_r' => 'fa-angle-left',
                'id' => 3,
                'nombre' => 'Compras',
                'option_id' => NULL,
                'orden' => 0,
                'ruta' => 'x',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            3 =>
            array (
                'color' => 'bg-purple',
                'created_at' => '2017-04-13 22:39:13',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-cart-arrow-down',
                'icono_r' => NULL,
                'id' => 4,
                'nombre' => 'Ingreso Compra',
                'option_id' => 3,
                'orden' => 1,
                'ruta' => 'compras.create',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            4 =>
            array (
                'color' => 'bg-warning',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => 'Administración de proveedores',
                'dev' => 0,
                'icono_l' => 'fa-user-tie',
                'icono_r' => NULL,
                'id' => 5,
                'nombre' => 'Proveedores',
                'option_id' => 3,
                'orden' => 3,
                'ruta' => 'proveedores.index',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            5 =>
            array (
                'color' => 'bg-teal',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => 'Ingresos de artículos a inventario',
                'dev' => 0,
                'icono_l' => 'fa-search',
                'icono_r' => NULL,
                'id' => 6,
                'nombre' => 'Buscar Compras',
                'option_id' => 3,
                'orden' => 2,
                'ruta' => 'compras.index',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            6 =>
            array (
                'color' => 'bg-secondary',
                'created_at' => '2018-07-30 23:17:58',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-dolly-flatbed',
                'icono_r' => 'fa-angle-left',
                'id' => 7,
                'nombre' => 'Requisiciones',
                'option_id' => NULL,
                'orden' => 4,
                'ruta' => 'x',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            7 =>
            array (
                'color' => 'bg-primary',
                'created_at' => '2018-07-30 23:19:08',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-plus-square',
                'icono_r' => NULL,
                'id' => 8,
                'nombre' => 'Nueva Requisición',
                'option_id' => 7,
                'orden' => 5,
                'ruta' => 'solicitudes.create',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            8 =>
            array (
                'color' => 'bg-warning',
                'created_at' => '2018-07-31 00:19:54',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-file-contract',
                'icono_r' => NULL,
                'id' => 9,
                'nombre' => 'Mis Requisiciones',
                'option_id' => 7,
                'orden' => 7,
                'ruta' => 'solicitudes.usuario',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            9 =>
            array (
                'color' => 'bg-info',
                'created_at' => '2018-07-31 00:16:45',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-dolly',
                'icono_r' => NULL,
                'id' => 10,
                'nombre' => 'Despachar Requisición',
                'option_id' => 7,
                'orden' => 9,
                'ruta' => 'solicitudes.despachar',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            10 =>
            array (
                'color' => 'bg-info',
                'created_at' => '2018-07-31 00:32:26',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-search',
                'icono_r' => NULL,
                'id' => 11,
                'nombre' => 'Buscar Requisición',
                'option_id' => 7,
                'orden' => 6,
                'ruta' => 'solicitudes.index',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            11 =>
            array (
                'color' => 'bg-secondary',
                'created_at' => '2018-08-08 02:28:11',
                'deleted_at' => '2022-12-06 08:09:21',
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-people-carry',
                'icono_r' => NULL,
                'id' => 12,
                'nombre' => 'Usuarios despachan',
                'option_id' => 7,
                'orden' => 13,
                'ruta' => 'user.despacha.user',
                'updated_at' => '2022-12-06 08:09:21',
            ),
            12 =>
            array (
                'color' => 'bg-info',
                'created_at' => '2019-07-01 22:29:53',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-barcode',
                'icono_r' => 'fa-angle-left',
                'id' => 13,
                'nombre' => 'Artículos',
                'option_id' => NULL,
                'orden' => 10,
                'ruta' => 'x',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            13 =>
            array (
                'color' => 'bg-primary',
                'created_at' => '2020-03-22 14:53:43',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-plus',
                'icono_r' => NULL,
                'id' => 14,
                'nombre' => 'Nuevo Artículo',
                'option_id' => 13,
                'orden' => 12,
                'ruta' => 'items.create',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            14 =>
            array (
                'color' => 'bg-success',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => 'Administración de los artículos',
                'dev' => 0,
                'icono_l' => 'fa-barcode',
                'icono_r' => NULL,
                'id' => 15,
                'nombre' => 'Buscar Artículo',
                'option_id' => 13,
                'orden' => 11,
                'ruta' => 'items.index',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            15 =>
            array (
                'color' => 'bg-orange',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => 'Administración de las categorías de los articulos',
                'dev' => 0,
                'icono_l' => 'fa-folder',
                'icono_r' => NULL,
                'id' => 16,
                'nombre' => 'Categorías',
                'option_id' => 13,
                'orden' => 15,
                'ruta' => 'itemCategorias.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            16 =>
            array (
                'color' => 'bg-warning',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => 'Administración de las unidades de medida',
                'dev' => 0,
                'icono_l' => 'fa-balance-scale',
                'icono_r' => NULL,
                'id' => 17,
                'nombre' => 'Unidades de medida',
                'option_id' => 13,
                'orden' => 16,
                'ruta' => 'unimeds.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            17 =>
            array (
                'color' => 'bg-warning',
                'created_at' => '2017-05-19 23:20:31',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-tags',
                'icono_r' => NULL,
                'id' => 18,
                'nombre' => 'Marcas',
                'option_id' => 13,
                'orden' => 14,
                'ruta' => 'marcas.index',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            18 =>
            array (
                'color' => 'bg-primary',
                'created_at' => '2017-07-28 16:26:22',
                'deleted_at' => NULL,
                'descripcion' => 'Magnitudes unidades de medida',
                'dev' => 0,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'id' => 19,
                'nombre' => 'Magnitud U/M',
                'option_id' => 13,
                'orden' => 17,
                'ruta' => 'magnitudes.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            19 =>
            array (
                'color' => 'bg-success',
                'created_at' => '2020-10-15 15:25:15',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-file-import',
                'icono_r' => NULL,
                'id' => 20,
                'nombre' => 'Importar Excel',
                'option_id' => 13,
                'orden' => 13,
                'ruta' => 'items.importar',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            20 =>
            array (
                'color' => 'bg-warning',
                'created_at' => '2018-03-20 23:14:39',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-balance-scale-left',
                'icono_r' => NULL,
                'id' => 21,
                'nombre' => 'Traslado entre unidades',
                'option_id' => 13,
                'orden' => 18,
                'ruta' => 'itemTraslados.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            21 =>
            array (
                'color' => 'bg-purple',
                'created_at' => '2018-09-09 19:53:29',
                'deleted_at' => '2022-07-27 12:48:06',
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-exclamation-triangle',
                'icono_r' => NULL,
                'id' => 22,
                'nombre' => 'Stock crítico',
                'option_id' => 13,
                'orden' => 20,
                'ruta' => 'stock.critico',
                'updated_at' => '2022-07-27 12:48:06',
            ),
            22 =>
            array (
                'color' => 'bg-orange',
                'created_at' => '2018-01-30 21:17:33',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'text-purple fa-chart-line',
                'icono_r' => 'fa-angle-left',
                'id' => 23,
                'nombre' => 'Reportes',
                'option_id' => NULL,
                'orden' => 19,
                'ruta' => 'x',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            23 =>
            array (
                'color' => 'bg-warning',
                'created_at' => '2018-09-29 17:39:32',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa fa-boxes',
                'icono_r' => NULL,
                'id' => 24,
                'nombre' => 'Stock',
                'option_id' => 23,
                'orden' => 0,
                'ruta' => 'reportes.stock',
                'updated_at' => '2022-12-20 23:57:58',
            ),
            24 =>
            array (
                'color' => 'bg-info',
                'created_at' => '2018-02-06 18:52:48',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-clipboard-list',
                'icono_r' => NULL,
                'id' => 25,
                'nombre' => 'Kardex',
                'option_id' => 23,
                'orden' => 1,
                'ruta' => 'reportes.kardex',
                'updated_at' => '2022-12-20 23:57:58',
            ),
            25 =>
            array (
                'color' => 'bg-success',
                'created_at' => '2020-03-25 19:35:47',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'id' => 26,
                'nombre' => 'Artículos A Vencer',
                'option_id' => 23,
                'orden' => 2,
                'ruta' => 'reportes.items.vencen',
                'updated_at' => '2022-12-20 23:57:58',
            ),
            26 =>
            array (
                'color' => 'bg-warning',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => 'Opciones de administración',
                'dev' => 0,
                'icono_l' => 'fa-folder',
                'icono_r' => 'fa-angle-left',
                'id' => 27,
                'nombre' => 'Admin',
                'option_id' => NULL,
                'orden' => 23,
                'ruta' => 'x',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            27 =>
            array (
                'color' => 'bg-orange',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => 'Administración de usuarios',
                'dev' => 0,
                'icono_l' => 'fa-users',
                'icono_r' => NULL,
                'id' => 28,
                'nombre' => 'Usuarios',
                'option_id' => 27,
                'orden' => 24,
                'ruta' => 'users.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            28 =>
            array (
                'color' => 'bg-orange',
                'created_at' => '2017-04-10 03:53:18',
                'deleted_at' => NULL,
                'descripcion' => 'Administración de los roles de los usuarios',
                'dev' => 0,
                'icono_l' => 'fa-user-tag',
                'icono_r' => NULL,
                'id' => 29,
                'nombre' => 'Roles',
                'option_id' => 27,
                'orden' => 26,
                'ruta' => 'roles.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            29 =>
            array (
                'color' => 'bg-primary',
                'created_at' => '2020-03-13 14:55:36',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-key',
                'icono_r' => NULL,
                'id' => 30,
                'nombre' => 'Permisos',
                'option_id' => 27,
                'orden' => 25,
                'ruta' => 'permissions.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            30 =>
            array (
                'color' => 'bg-teal',
                'created_at' => '2017-05-21 14:36:26',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-cogs',
                'icono_r' => NULL,
                'id' => 31,
                'nombre' => 'Configuraciones',
                'option_id' => 27,
                'orden' => 27,
                'ruta' => 'profile.business',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            31 =>
            array (
                'color' => 'bg-info',
                'created_at' => '2022-08-05 10:49:49',
                'deleted_at' => '2022-12-08 08:46:08',
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-stamp',
                'icono_r' => NULL,
                'id' => 32,
                'nombre' => 'Autorizar Requisición',
                'option_id' => 7,
                'orden' => 10,
                'ruta' => 'solicitudes.autorizar',
                'updated_at' => '2022-12-08 08:46:08',
            ),
            32 =>
            array (
                'color' => 'bg-primary',
                'created_at' => '2022-08-06 08:57:05',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-stamp',
                'icono_r' => NULL,
                'id' => 33,
                'nombre' => 'Aprobar Reqisición',
                'option_id' => 7,
                'orden' => 8,
                'ruta' => 'solicitudes.aprobar',
                'updated_at' => '2022-12-08 08:48:01',
            ),
            33 =>
            array (
                'color' => 'bg-purple',
                'created_at' => '2022-08-29 16:56:26',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-book',
                'icono_r' => NULL,
                'id' => 34,
                'nombre' => 'Inventarios',
                'option_id' => NULL,
                'orden' => 28,
                'ruta' => 'x',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            34 =>
            array (
                'color' => 'bg-orange',
                'created_at' => '2022-08-29 22:14:51',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-computer',
                'icono_r' => NULL,
                'id' => 35,
                'nombre' => 'Activos fijos',
                'option_id' => 34,
                'orden' => 29,
                'ruta' => 'activos.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            35 =>
            array (
                'color' => 'bg-primary',
                'created_at' => '2022-08-29 16:58:20',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-address-book',
                'icono_r' => NULL,
                'id' => 36,
                'nombre' => 'Tarjeta de responsabilidad',
                'option_id' => 34,
                'orden' => 30,
                'ruta' => 'activoTarjetas.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            36 =>
            array (
                'color' => 'bg-success',
                'created_at' => '2022-08-29 17:01:47',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-hashtag',
                'icono_r' => NULL,
                'id' => 37,
                'nombre' => 'Ingreso de código de inventario 1h',
                'option_id' => 34,
                'orden' => 32,
                'ruta' => 'inventario.1h',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            37 =>
            array (
                'color' => 'bg-info',
                'created_at' => '2022-08-29 17:03:40',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-file-contract',
                'icono_r' => NULL,
                'id' => 38,
                'nombre' => 'Solicitud de cargo o descargo de bienes',
                'option_id' => 34,
                'orden' => 33,
                'ruta' => 'activoSolicitudes.index',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            38 =>
            array (
                'color' => 'bg-success',
                'created_at' => '2022-08-29 17:04:35',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'id' => 39,
                'nombre' => 'Reporte Bienes por unidad',
                'option_id' => 34,
                'orden' => 34,
                'ruta' => 'reporte.bienes.unidad',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            39 =>
            array (
                'color' => NULL,
                'created_at' => '2022-09-08 15:38:36',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-file-import',
                'icono_r' => NULL,
                'id' => 40,
                'nombre' => 'Importar Excel',
                'option_id' => 34,
                'orden' => 31,
                'ruta' => 'activos.importar',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            40 =>
            array (
                'color' => NULL,
                'created_at' => '2022-12-08 08:47:18',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-users',
                'icono_r' => NULL,
                'id' => 41,
                'nombre' => 'Recursos Humanos',
                'option_id' => NULL,
                'orden' => 35,
                'ruta' => 'x',
                'updated_at' => '2022-12-08 08:48:02',
            ),
            41 =>
            array (
                'color' => NULL,
                'created_at' => '2022-12-08 08:49:00',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-user-tie',
                'icono_r' => NULL,
                'id' => 42,
                'nombre' => 'Colaboradores',
                'option_id' => 41,
                'orden' => 0,
                'ruta' => 'colaboradores.index',
                'updated_at' => '2022-12-08 08:50:55',
            ),
            42 =>
            array (
                'color' => NULL,
                'created_at' => '2022-12-20 23:52:04',
                'deleted_at' => NULL,
                'descripcion' => NULL,
                'dev' => 0,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'id' => 43,
                'nombre' => 'Libro Almacen',
                'option_id' => 23,
                'orden' => 3,
                'ruta' => 'reportes.libro.almacen',
                'updated_at' => '2022-12-20 23:57:58',
            ),
        ));

        \DB::statement('SET FOREIGN_KEY_CHECKS=1');

    }
}
