<?php

namespace Database\Seeders;

use App\Models\Bodega;
use Illuminate\Database\Seeder;

class RrhhUnidadesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('rrhh_unidades')->delete();

        \DB::table('rrhh_unidades')->insert(array (
            0 =>
            array (
                'id' => 1,
                'codigo' => '100000',
                'nombre' => 'Secretaría',
                'centro_id' => NULL,
                'unidad_tipo_id' => 1,
                'unidad_padre_id' => NULL,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'codigo' => '101000',
                'nombre' => 'Despacho superior',
                'centro_id' => NULL,
                'unidad_tipo_id' => 3,
                'unidad_padre_id' => 1,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'codigo' => '101001',
                'nombre' => 'Asistencia de despacho superior',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 2,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'codigo' => '102000',
                'nombre' => 'Órganos de asesoría y de apoyo técnico',
                'centro_id' => NULL,
                'unidad_tipo_id' => 3,
                'unidad_padre_id' => 1,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'codigo' => '102100',
                'nombre' => 'Dirección de asesoría jurídica',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 4,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'codigo' => '102101',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 5,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'codigo' => '102200',
                'nombre' => 'Dirección de planificación',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 4,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'codigo' => '102201',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 7,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'codigo' => '102300',
                'nombre' => 'Dirección de comunicación social',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 4,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'codigo' => '102301',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 9,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'codigo' => '102400',
                'nombre' => 'Dirección de informática',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 4,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'codigo' => '102401',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 11,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'codigo' => '102500',
                'nombre' => 'Unidad de genero',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 4,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'codigo' => '102501',
                'nombre' => 'Asistencia de unidad',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 13,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'codigo' => '103000',
                'nombre' => 'Órganos de administración',
                'centro_id' => NULL,
                'unidad_tipo_id' => 3,
                'unidad_padre_id' => 1,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'codigo' => '103100',
                'nombre' => 'Dirección de recursos humanos',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 15,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'codigo' => '103101',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 16,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'codigo' => '103110',
                'nombre' => 'Departamento de gestión de personal',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 16,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'codigo' => '103111',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 18,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'codigo' => '103120',
                'nombre' => 'Departamento de nóminas',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 16,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'codigo' => '103121',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 20,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'codigo' => '103130',
                'nombre' => 'Departamento de capacitación',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 16,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'codigo' => '103131',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 22,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'codigo' => '103200',
                'nombre' => 'Dirección administrativa',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 15,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'codigo' => '103201',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 24,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'codigo' => '103210',
                'nombre' => 'Departamento de compras',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 24,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'codigo' => '103211',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 26,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'codigo' => '103220',
                'nombre' => 'Departamento de servicios generales y de transporte',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 24,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'codigo' => '103221',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 28,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'codigo' => '103230',
                'nombre' => 'Departamento de almacén',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 24,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'codigo' => '103231',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 30,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'codigo' => '103240',
                'nombre' => 'Departamento de seguridad',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 24,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'codigo' => '103241',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 32,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'codigo' => '103300',
                'nombre' => 'Dirección financiera',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 15,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'codigo' => '103301',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 34,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'codigo' => '103310',
                'nombre' => 'Departamento de presupuesto',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 34,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'codigo' => '103311',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 36,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'codigo' => '103320',
                'nombre' => 'Departamento de contabilidad',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 34,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'codigo' => '103321',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 38,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'codigo' => '103330',
                'nombre' => 'Departamento de tesorería',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 34,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'codigo' => '103331',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 40,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'codigo' => '103340',
                'nombre' => 'Departamento de inventarios',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 34,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'codigo' => '103341',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 42,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'codigo' => '104000',
                'nombre' => 'Órganos de desconcentración',
                'centro_id' => NULL,
                'unidad_tipo_id' => 3,
                'unidad_padre_id' => 1,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'codigo' => '104100',
                'nombre' => 'Dirección departamental',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 44,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'codigo' => '104101',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 45,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'codigo' => '104110',
                'nombre' => 'Departamento de coordinación técnica',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 45,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'codigo' => '104111',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 47,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'codigo' => '104120',
                'nombre' => 'Sedes departamentales',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 45,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'codigo' => '104121',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 49,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'codigo' => '105000',
                'nombre' => 'Órganos de control interno',
                'centro_id' => NULL,
                'unidad_tipo_id' => 3,
                'unidad_padre_id' => 1,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'codigo' => '105100',
                'nombre' => 'Dirección de auditoría',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 51,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'codigo' => '105101',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 52,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'codigo' => '110000',
                'nombre' => 'Subsecretaría de preservación familiar, fortalecimiento y apoyo comunitario',
                'centro_id' => NULL,
                'unidad_tipo_id' => 2,
                'unidad_padre_id' => 1,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'codigo' => '111000',
                'nombre' => 'Despacho subsecretaría de preservación familiar, fortalecimiento y apoyo comunitario',
                'centro_id' => NULL,
                'unidad_tipo_id' => 3,
                'unidad_padre_id' => 54,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'codigo' => '111001',
                'nombre' => 'Asistencia de subsecretaría',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 55,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'codigo' => '111100',
                'nombre' => 'Dirección de atención a niñas, niños y adolescentes con discapacidad',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 55,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'codigo' => '111101',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 57,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'codigo' => '111110',
                'nombre' => 'Departamento de atención a la niñez y adolescencia con discapacidad',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 57,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'codigo' => '111111',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 59,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'codigo' => '111112',
                'nombre' => 'Centro de atención especial Alida España de Arana',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 59,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'codigo' => '111113',
                'nombre' => 'Centro de capacitación ocupacional -CCO-',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 59,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'codigo' => '111114',
                'nombre' => 'Centro de educación especial San Cristóbal Totonicapán',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 59,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            63 =>
            array (
                'id' => 64,
                'codigo' => '111115',
                'nombre' => 'Centro de educación especial San Juan Bautista',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 59,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            64 =>
            array (
                'id' => 65,
                'codigo' => '111120',
                'nombre' => 'Departamento de subsidios familiares',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 57,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            65 =>
            array (
                'id' => 66,
                'codigo' => '111121',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 65,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            66 =>
            array (
                'id' => 67,
                'codigo' => '111200',
                'nombre' => 'Dirección de primera infancia',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 55,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            67 =>
            array (
                'id' => 68,
                'codigo' => '111201',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 67,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            68 =>
            array (
                'id' => 69,
                'codigo' => '111210',
                'nombre' => 'Departamento de centros de atención integral',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 67,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            69 =>
            array (
                'id' => 70,
                'codigo' => '111211',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            70 =>
            array (
                'id' => 71,
                'codigo' => '111212',
                'nombre' => 'CAI Colón',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            71 =>
            array (
                'id' => 72,
                'codigo' => '111213',
                'nombre' => 'CAI Bolívar',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            72 =>
            array (
                'id' => 73,
                'codigo' => '111214',
                'nombre' => 'CAI Presidenta',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            73 =>
            array (
                'id' => 74,
                'codigo' => '111215',
                'nombre' => 'CAI Villa Nueva',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            74 =>
            array (
                'id' => 75,
                'codigo' => '111216',
                'nombre' => 'CAI Zona 3',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            75 =>
            array (
                'id' => 76,
                'codigo' => '111217',
                'nombre' => 'CAI Terminal',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            76 =>
            array (
                'id' => 77,
                'codigo' => '111218',
                'nombre' => 'CAI Zona 5',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            77 =>
            array (
                'id' => 78,
                'codigo' => '111219',
                'nombre' => 'CAI Zona 6',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            78 =>
            array (
                'id' => 79,
                'codigo' => '1112110',
                'nombre' => 'CAI Parroquia',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            79 =>
            array (
                'id' => 80,
                'codigo' => '1112111',
                'nombre' => 'CAI Bethania',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            80 =>
            array (
                'id' => 81,
                'codigo' => '1112112',
                'nombre' => 'CAI San Miguel Petapa',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            81 =>
            array (
                'id' => 82,
                'codigo' => '1112113',
                'nombre' => 'CAI Zona 19',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            82 =>
            array (
                'id' => 83,
                'codigo' => '1112114',
                'nombre' => 'CAI San Pedro Ayampuc',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            83 =>
            array (
                'id' => 84,
                'codigo' => '1112115',
                'nombre' => 'CAI Mixco',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            84 =>
            array (
                'id' => 85,
                'codigo' => '1112116',
                'nombre' => 'CAI San Pero Sacatepequez',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            85 =>
            array (
                'id' => 86,
                'codigo' => '1112117',
                'nombre' => 'CAI Peronia',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            86 =>
            array (
                'id' => 87,
                'codigo' => '1112118',
                'nombre' => 'CAI Guastatoya',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            87 =>
            array (
                'id' => 88,
                'codigo' => '1112119',
                'nombre' => 'CAI Chimaltenango',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            88 =>
            array (
                'id' => 89,
                'codigo' => '1112120',
                'nombre' => 'CAI Escuintla',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            89 =>
            array (
                'id' => 90,
                'codigo' => '1112121',
                'nombre' => 'CAI Cuilapa',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            90 =>
            array (
                'id' => 91,
                'codigo' => '1112122',
                'nombre' => 'CAI Sololá',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            91 =>
            array (
                'id' => 92,
                'codigo' => '1112123',
                'nombre' => 'CAI Totonicapán',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            92 =>
            array (
                'id' => 93,
                'codigo' => '1112124',
                'nombre' => 'CAI Quetzaltenango',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            93 =>
            array (
                'id' => 94,
                'codigo' => '1112125',
                'nombre' => 'CAI Mazatenango',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            94 =>
            array (
                'id' => 95,
                'codigo' => '1112126',
                'nombre' => 'CAI San Juan Bautista',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            95 =>
            array (
                'id' => 96,
                'codigo' => '1112127',
                'nombre' => 'CAI Retalhuleu',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            96 =>
            array (
                'id' => 97,
                'codigo' => '1112128',
                'nombre' => 'CAI San Marcos',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            97 =>
            array (
                'id' => 98,
                'codigo' => '1112129',
                'nombre' => 'CAI San Pedro San Marcos',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            98 =>
            array (
                'id' => 99,
                'codigo' => '1112130',
                'nombre' => 'CAI Comitancillo San Marcos',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            99 =>
            array (
                'id' => 100,
                'codigo' => '1112131',
                'nombre' => 'CAI Concepción Tutuapa',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            100 =>
            array (
                'id' => 101,
                'codigo' => '1112132',
                'nombre' => 'CAI Huehuetenango',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            101 =>
            array (
                'id' => 102,
                'codigo' => '1112133',
                'nombre' => 'CAI Quiché',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            102 =>
            array (
                'id' => 103,
                'codigo' => '1112134',
                'nombre' => 'CAI Salamá',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            103 =>
            array (
                'id' => 104,
                'codigo' => '1112135',
                'nombre' => 'CAI Cobán',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            104 =>
            array (
                'id' => 105,
                'codigo' => '1112136',
                'nombre' => 'CAI Puerto Barrios',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            105 =>
            array (
                'id' => 106,
                'codigo' => '1112137',
                'nombre' => 'CAI Zacapa',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            106 =>
            array (
                'id' => 107,
                'codigo' => '1112138',
                'nombre' => 'CAI Río Hondo',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:49',
                'updated_at' => '2025-08-18 17:37:49',
                'deleted_at' => NULL,
            ),
            107 =>
            array (
                'id' => 108,
                'codigo' => '1112139',
                'nombre' => 'CAI Chiquimula',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            108 =>
            array (
                'id' => 109,
                'codigo' => '1112140',
                'nombre' => 'CAI Esquipulas',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            109 =>
            array (
                'id' => 110,
                'codigo' => '1112141',
                'nombre' => 'CAI Jutiapa',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            110 =>
            array (
                'id' => 111,
                'codigo' => '1112142',
                'nombre' => 'CAI Jalapa',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            111 =>
            array (
                'id' => 112,
                'codigo' => '1112143',
                'nombre' => 'CAI Coatepeque',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            112 =>
            array (
                'id' => 113,
                'codigo' => '1112144',
                'nombre' => 'CAI Petén',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            113 =>
            array (
                'id' => 114,
                'codigo' => '1112145',
                'nombre' => 'CAI Jícaro',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 69,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            114 =>
            array (
                'id' => 115,
                'codigo' => '111220',
                'nombre' => 'Departamento de educando en familia',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 67,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            115 =>
            array (
                'id' => 116,
                'codigo' => '111221',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 115,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            116 =>
            array (
                'id' => 117,
                'codigo' => '111230',
                'nombre' => 'Departamento de regulación de centros de cuidado infantil diario',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 67,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            117 =>
            array (
                'id' => 118,
                'codigo' => '111231',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 117,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            118 =>
            array (
                'id' => 119,
                'codigo' => '120000',
                'nombre' => 'Subsecretaría de reinserción y resocialización de adolescentes en conflicto con la ley penal',
                'centro_id' => NULL,
                'unidad_tipo_id' => 2,
                'unidad_padre_id' => 1,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            119 =>
            array (
                'id' => 120,
                'codigo' => '121000',
                'nombre' => 'Despacho subsecretaría de reinserción y resocialización de adolescentes en conflicto con la ley penal',
                'centro_id' => NULL,
                'unidad_tipo_id' => 3,
                'unidad_padre_id' => 119,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            120 =>
            array (
                'id' => 121,
                'codigo' => '121001',
                'nombre' => 'Asistencia de subsecretaría',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 120,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            121 =>
            array (
                'id' => 122,
                'codigo' => '121100',
                'nombre' => 'Dirección de centros especializados de privación de libertad',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 120,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            122 =>
            array (
                'id' => 123,
                'codigo' => '121101',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 122,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            123 =>
            array (
                'id' => 124,
                'codigo' => '121102',
                'nombre' => 'Centro Especializado de Reinsercion -CER 1-',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 122,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            124 =>
            array (
                'id' => 125,
                'codigo' => '121103',
            'nombre' => 'Centro Juvenil de Detención Provisional CEJUDEP (Gaviotas)',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 122,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            125 =>
            array (
                'id' => 126,
                'codigo' => '121104',
                'nombre' => 'Centro Juvenil de Privación de Libertad para Mujeres CEJUPLIM',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 122,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            126 =>
            array (
                'id' => 127,
                'codigo' => '121105',
                'nombre' => 'Centro Juvenil de Privación de Libertad para Varones CEJUPLIV (Etapa
II)',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 122,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            127 =>
            array (
                'id' => 128,
                'codigo' => '121106',
                'nombre' => 'Centro especializado de Reinserción –CER',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 122,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            128 =>
            array (
                'id' => 129,
                'codigo' => '121107',
                'nombre' => 'Casa Intermedia',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 122,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            129 =>
            array (
                'id' => 130,
                'codigo' => '121200',
                'nombre' => 'Dirección de medidas socioeducativas',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 120,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            130 =>
            array (
                'id' => 131,
                'codigo' => '121201',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 130,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            131 =>
            array (
                'id' => 132,
                'codigo' => '121202',
                'nombre' => 'Centro de Capacitación y Formación Integral –CCFI',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 130,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            132 =>
            array (
                'id' => 133,
                'codigo' => '121300',
                'nombre' => 'Dirección de operaciones y logística',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 120,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            133 =>
            array (
                'id' => 134,
                'codigo' => '121301',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 133,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            134 =>
            array (
                'id' => 135,
                'codigo' => '121302',
                'nombre' => 'CALL Center',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 133,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            135 =>
            array (
                'id' => 136,
                'codigo' => '121400',
                'nombre' => 'Dirección de prevención terciaria',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 120,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            136 =>
            array (
                'id' => 137,
                'codigo' => '121401',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 136,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            137 =>
            array (
                'id' => 138,
                'codigo' => '121402',
                'nombre' => 'Prevención Terciaria',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 136,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            138 =>
            array (
                'id' => 139,
                'codigo' => '130000',
                'nombre' => 'Subsecretaría de protección y acogimiento a la niñez y adolescencia',
                'centro_id' => NULL,
                'unidad_tipo_id' => 2,
                'unidad_padre_id' => 1,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            139 =>
            array (
                'id' => 140,
                'codigo' => '131000',
                'nombre' => 'Despacho subsecretaría de protección y acogimiento a la niñez y adolescencia',
                'centro_id' => NULL,
                'unidad_tipo_id' => 3,
                'unidad_padre_id' => 139,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            140 =>
            array (
                'id' => 141,
                'codigo' => '131001',
                'nombre' => 'Asistencia de subsecretaría',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 140,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            141 =>
            array (
                'id' => 142,
                'codigo' => '131100',
                'nombre' => 'Dirección de protección especial, acogimiento familiar y residencial',
                'centro_id' => NULL,
                'unidad_tipo_id' => 4,
                'unidad_padre_id' => 140,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            142 =>
            array (
                'id' => 143,
                'codigo' => '131101',
                'nombre' => 'Asistencia de dirección',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 142,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            143 =>
            array (
                'id' => 144,
                'codigo' => '131110',
            'nombre' => 'Departamento de acogimiento familiar temporal (familias sustitutas)',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 142,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            144 =>
            array (
                'id' => 145,
                'codigo' => '131111',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 144,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            145 =>
            array (
                'id' => 146,
                'codigo' => '131120',
                'nombre' => 'Departamento de protección a la niñez y adolescencia con capacidades diferentes severa y profunda',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 142,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            146 =>
            array (
                'id' => 147,
                'codigo' => '131121',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 146,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            147 =>
            array (
                'id' => 148,
                'codigo' => '131130',
                'nombre' => 'Departamento de protección especial de primera infancia',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 142,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            148 =>
            array (
                'id' => 149,
                'codigo' => '131131',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 148,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            149 =>
            array (
                'id' => 150,
                'codigo' => '131140',
                'nombre' => 'Departamento de protección a la niñez y adolescencia victima de violencia sexual con enfoque de género',
                'centro_id' => NULL,
                'unidad_tipo_id' => 5,
                'unidad_padre_id' => 142,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'no',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
            150 =>
            array (
                'id' => 151,
                'codigo' => '131141',
                'nombre' => 'Asistencia de departamento',
                'centro_id' => NULL,
                'unidad_tipo_id' => 6,
                'unidad_padre_id' => 150,
                'jefe_id' => NULL,
                'activa' => 'si',
                'solicita' => 'si',
                'created_at' => '2025-08-18 17:37:50',
                'updated_at' => '2025-08-18 17:37:50',
                'deleted_at' => NULL,
            ),
        ));

        $unidades = \App\Models\RrhhUnidad::get();

        foreach ($unidades as $unidad) {
            Bodega::create([
                'nombre' => $unidad->nombre
            ]);
        }

    }
}
